- .travis.yml
- Makefile
- scripts/coverage.sh
The coverage.sh is from codecov. Once 1.10 lands, we'll no longer need
it.
There are currently issues with < Go 1.9 on Linux which we will need to fix separately.
> Add travis/codecov for pre-commit validation

- testmain.go
Hi @prashantv 
Adding indentation to fix the rendering of the code example in the docs.
> Indent a code example in a comment

- doc.go
- internal/stack/doc.go
Add `doc.go` with custom import comment, and `goleak` package comment.
> doc: add doc.go with custom import comment

- leaks_test.go
- options.go
When t.Parallel is used, tests are queued to run after all serially
executed tests are run. This causes issues if the serial test tries to
verify goroutines.
Fixes #16
> Ignore t.Parallel goroutines, they represent queued tests

- README.md
When first adding a VerifyTestMain, the package may have leaks with
unclear sources. Running tests one-at-a-time can help determine the
source of the leak.
> Add note on how to find single leaky test

- .travis.yml
- Makefile
- leaks_test.go
* Fix golint + go vet to work with latest version
* Fix correctly detected bug where `fmt.Sprint` was not used correctly.
>  Add latest versions to Travis, support 1.10+ only

- internal/stack/stacks_test.go
- options_test.go
- utils_test.go
Some tests assume that stack.All() will give a stable set of goroutines:
that any background goroutines from the test framework/previous tests
have run till they're blocked.
Add verification that stack.All() returns a "stable" set of stacks
before running these tests.
> Fix flaky tests

- Makefile
- options.go
When running tests with `-trace`, a background
goroutine blocks on `runtime.ReadTrace`:
```
Goroutine 20 in state trace reader (blocked), with runtime.goparkunlock on top of the stack:
goroutine 20 [trace reader (blocked)]:
runtime.goparkunlock(...)
(truncated)/go1.13.linux.amd64/src/runtime/proc.go:310
runtime.ReadTrace(0xc00008e048, 0xc0000160d0, 0x10)
(truncated)/go1.13.linux.amd64/src/runtime/trace.go:395 +0x4ed
runtime/trace.Start.func1(0x7b3dc0, 0xc00008e048)
(truncated)/go1.13.linux.amd64/src/runtime/trace/trace.go:129 +0x47
created by runtime/trace.Start
(truncated)/go1.13.linux.amd64/src/runtime/trace/trace.go:127 +0xd8
```
Skip this stack by default. Run tests with `-trace` enabled to verify
that this stack should be skipped.
Fixes #39.
> Ignore blocked trace stack by default

- README.md
Since we've tagged a 1.0, we can consider this library stable.
I've moved the stability section to the bottom since it's no longer
needed as a deterrent near the top.
> README: Mark as stable

- .travis.yml
This PR updates travis to run tests on Go 1.14 since the stable version is out.
> Run tests on Go 1.14

- README.md
Hi there, thanks for the amazing tool!
I insert following code into one of my package test files:
```
func TestMain(m *testing.M) {
goleak.VerifyTestMain(m)
}
```
Then on tests run:
```
$ go test -count=1 ./...
PASS
goleak: Errors on successful test run: found unexpected goroutines:
<...>
```
I've tried the following command to identify the problem:
```
$ go test -c -o tests
$ for test in $(go test -list . | grep "^Test"); do ./tests -test.run "^$test\$" &>/dev/null && echo -n "." || echo "\n$test failed"; done
.....................................%      
```
And here is behavior after applying the adjusted command from this PR:
```
for test in $(go test -list . | grep -E "^(Test|Example)"); do ./tests -test.run "^$test\$" &>/dev/null && echo -n "." || echo "\n$test failed"; done …
```
> Add Examples to failing tests check

- leaks_test.go
- options.go
This allows usage specific tests in big projects that recently started to use go-leak check.
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
https://github.com/uber-go/goleak/issues/48
> Add option to ignore current goroutines

- .github/workflows/go.yml
- signal_test.go
- tools_test.go
Start testing against Go 1.17. 
Changes were also made to a couple of test files to make them pass the linters in Go 1.17
> CI: Test against Go 1.17

- options.go
- tracestack_new.go
- tracestack_old.go
This fixes #66 . 
On newer Go versions (1.16 onwards), the top of trace stacks is no longer `runtime.goparkunlock`. We had a logic that relied on this being the case, which made the tests to fail with `-trace` flag for newer Go versions. However, to maintain backwards compatibility, we shouldn't just remove this check.
This separates out the `isTraceStack` into a separate file that gets conditionally compiled on different Go versions (`tracestack_old.go` for Go 1.15 and before and `tracestack_new.go` for Go 1.16 and newer) to address this issue.
Internal Ref: GO-887.
> Fix isTraceStack on newer Go versions

- .github/workflows/go.yml
- go.mod
- go.sum
We only support the two most recent minor releases.
> CI: test with Go 1.17 and 1.18

- leaks.go
Mark `VerifyNone(...)` as a test `Helper` function, so that it reports the error at the call site, rather than `leaks.go:78:`.
From the [go docs](https://pkg.go.dev/testing#T.Helper):
> Helper marks the calling function as a test helper function. When printing file and line information, that function will be skipped. Helper may be called simultaneously from multiple goroutines.
This is useful for tests that verify go routines at multiple points, so failures can be more easily distinguished.
> Mark VerifyNone as a test Helper

- leaks.go
- leaks_test.go
- options.go
- testmain.go
- testmain_test.go
This adds Cleanup option which can be passed to VerifyTestMain and
VerifyNone. This takes in a function that will be executed at the
end of the leak verification.
Internal Ref: GO-888
Fix #63
> Add Cleanup option

- README.md
Fixes #85
We're no longer compatible with pre 1.16  since #79.
I'm opting for removing the version rather than updating it to 1.18 since we already have go.mod for this. 
Adding a pointer to the Go release policy, but I also considered dropping the mentions altogether. Copied the copy from `zap`.
> Remove mentions of Go 1.5 compatibility from Readme

- Makefile
- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
- tools/tools.go
Fixes #92.
Avoid tools dependencies in goleak's go.mod.
golint is deprecated, we can separately migrate to another tool, but the tools change avoids any CI-time dependency from leaking into our go.mod.
> Move tools dependencies into subdirectory with tag

- .github/workflows/go.yml
- tools/go.mod
As part of this change, also upgrade the actions to the latest major versions.
This also fixes a typo in the tools/go.mod.
> Test against go1.20 (drop 1.17 and 1.18)..

- leaks.go
- leaks_test.go
- options.go
- options_test.go
Make goleak options more flexible to adapt to users' variety scenarios
Signed-off-by: Kante Yin <kerthcet@gmail.com>
fix  https://github.com/uber-go/goleak/issues/93
> Make maxSleep and maxRetires configurable when building options

- options.go
When Fuzz testing, if the `-fuzz` flag is used then the fuzzing engine is used to generate test cases out of the seed corpus, this causes `testing.runFuzzTests` to be blocked until a failing input is found or there is a signal to stop generating.
On the other hand `testing.runFuzzTests` is called even without the use of the `-fuzz` flag, executes the input testing with all the elements in the seed corpus and it's blocked until every test has run.
On both cases, goleak detects them as leaking goroutines, but this are expected goroutines.
Internal Ref: GO-2002
Fix #104
> Ignore testing.runFuzzing and testing.runFuzzTests

- leaks.go
It's a known issue that goleak is incompatible with tests being run in parallel.
* https://github.com/uber-go/goleak/issues/16
* https://github.com/uber-go/goleak/issues/83
Unfortunately, there is no real solution to this issue.
* https://github.com/uber-go/goleak/issues/16#issuecomment-575020250
* https://github.com/uber-go/goleak/issues/83#issuecomment-1487300420
* https://github.com/uber-go/goleak/issues/83#issuecomment-1755316283
This PR at least documents the incompatibility
and suggests using `VerifyTestMain` instead.
> Document incompatibility of VerifyNone with t.Parallel

- go.mod
- internal/stack/scan.go
- internal/stack/scan_test.go
- internal/stack/stacks.go
- internal/stack/stacks_test.go
In anticipation of parsing more information from stack traces make the
stack trace parsing logic more manageable by moving it from a state
machine into a layout closer to a recursive descent parser.
That is, instead of a central loop that reads input line-by-line
and needs to manage its various states:
current, result := ...
for {
input := read()
if cond(input) {
result.append(current)
current = startNew(input)
} else {
current = accumulate(input)
}
}
result = flush(current)
Break it down so that parsing of individual results is its own function,
representing the state machine via control flow.
result := ...
for {
input := read()
if cond(input) {
result.append(parseOne())
}
}
// where
func parseOne(input) {
value := ...
for ; !cond(input); input = read() {
value = accumulate(input)
} …
> internal/stack: Use control flow for state

- internal/stack/stacks.go
- internal/stack/stacks_test.go
- internal/stack/testdata/Makefile
- internal/stack/testdata/http.go
- internal/stack/testdata/http.go1.20.txt
- internal/stack/testdata/http.tracebackancestors.txt
- internal/stack/testdata/http.txt
Adds support to the stack parser for reading the full list of functions
for a stack trace.
NOTE:
This includes the function that created the stack trace;
it's the bottom of the stack.
We don't maintain the order of the functions
since that's not something we need at this time.
The functions are all placed in a set.
This unblocks #41 (PR incoming)
and allows implementing an IgnoreAnyFunction option
(similar to #80 that has since stalled).
Depends on #110
> stack: Parse all functions

- CHANGELOG.md
- options.go
- tracestack_new.go
Instead of matching for built-in functions with strings.Contains,
use the parsed stack information to match function names exactly.
Following this change, the only remaining strings.Contains are
to match on the goroutine state:
```
% rg strings.Contains
utils_test.go
84:             if strings.Contains(s.State(), "run") {
internal/stack/stacks_test.go
249:            if strings.Contains(s.State(), "run") {
```
Resolves #41
Depends on #111
> ignores: Don't use strings.Contains

- README.md
The CI job was renamed to ci.yml in #108
but the README.md was not updated.
Fix the badge URL in the README.
> README: Fix build status badge

- CHANGELOG.md
- options.go
- options_test.go
- utils_test.go
Adds a new IgnoreAnyFunction option to ignore stacks
that have the provided function anywhere in the stack,
not just the top.
To test this better, the helper blockedG.run function
was split into two.
Supersedes #80
Depends on #111
> options: Add IgnoreAnyFunction

- leaks.go
- leaks_test.go
- options.go
- options_test.go
This reverts commit 751da596f6f726bcc02401452bacb0fda8fc7b7b.
Per discussion in #93, we don't want to release this change as-is.
> Revert "Make maxSleep and maxRetires configurable when building options (#94)"

- internal/stack/stacks.go
- internal/stack/stacks_test.go
When parsing stacks we frequently encounter elided frames. The actual stack line looks something like `...23 frames elided...`, which is passed to `parseFuncName`, which of course is not parsable as a function name. As a result, whenever this happens we get a useless panic like the following:
```
panic: Failed to parse stack trace: parse function: no function found: "...23 frames elided..."
goroutine 1 [running]:
go.uber.org/goleak/internal/stack.getStackBuffer(0x1)
/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/stacks.go:240 +0x65
go.uber.org/goleak/internal/stack.getStacks(0x1)
/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/stacks.go:84 +0x3b
go.uber.org/goleak/internal/stack.All(...)
/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/sta …
```
> gracefully handle elided frames

- .github/workflows/ci.yml
Follow-up to #120, I accidentally merged the PR without waiting for all tests to run, and missed that 1.20 tests are failing.
Lint is failing because of how we skip golangci-lint run in the action and use the Makefile. Use the same logic as zap to skip lint.
Tests are failing on 1.20 as stack elision doesn't kick in for the test. From 1.21 onwards, it does kick in. Rather than try to make the test trigger stack elision on 1.20, let's bump the versions to 1.21 / 1.22.
> Fix lint and upgrade versions to 1.21/1.22

- .github/workflows/ci.yml
This upgrades codecov CI action to version 4,
and uses the codecov token when uploading,
since tokenless uploading is no longer supported for some cases.
> CI: Upgrade to codecov 4 & use token.

- .github/workflows/ci.yml
- .golangci.yml
This add explicit exemption for things we don't care about in errcheck lint message.
> update golangci-lint configuration

- leaks.go
- options.go
- testmain.go
- testmain_test.go
This adds an Option to run goleak when test runs fail.
Fixes #128.
> Add RunOnFailure option

- README.md
someone at Uber unfortunately spent cycles trying to convert VerifyTestMain call to VerifyNone(t) for individual cases only to find out that it doesn't work well with t.Parallel().
Even though VerifyNone(t)'s documentation already says this, it might be worth clarifying this in the README since the wording can make it sound like calling VerifyTestMain() vs calling VerifyNone() at the end of every single test case is completely identical in behavior.
> clarify README
